server:
  port: 9000

spring:

#  datasource:
#    url: jdbc:h2:tcp://localhost/~/deeply
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: 1111

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/deeply
    username: root
    password: 1111

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션
    open-in-view: true

  devtools:
    livereload:
      enabled: true

  mvc:
    path match:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

jwt:
  password: yunjinchoi
  secret : yunjinchoi
  access-expired : 83000
